### PR TITLE
Ensure babel-polyfill is built as part of the webpack build

### PR DESCRIPTION
**Pull request by joshnesbitt**

### CODE REVIEW

**Comment by joshnesbitt** [comment]
@romidane @thomaslloyd started going down this route as discussed [here](https://github.com/rollup/rollup/issues/616#issuecomment-215227630) to no avail. Any ideas on this would be appreciated as I'm quite unsure what's happening here.

**Comment by joshnesbitt** [comment]
I think this should be dealt with in the target project, therefore I'm going to scrap this and pull out the polyfill from the toolbelt. @thomaslloyd I wonder whether it's worth using a different polyfill to see if that works? @romidane mentioned he's had problems in the past.

**Comment by thomaslloyd** [comment]
I think that if you remove it completely from the toolbelt then the test script will break as that uses it too. I'll try to figure out a way to make it work later in the week. :)

**Comment by joshnesbitt** [comment]
Thanks @thomaslloyd! Ha just opened a new PR which removes it from the tests too. In theory we shouldn't be needing them in there?

**Pull request closed without merging**
