### PR TITLE
Get Mocha to run tests that use Enzyme

### PR DESCRIPTION
**Pull request by thomaslloyd**
Including some setup in the mocha config file so that it can run tests that use [Enzyme][0], a testing library for React. 

[0]: https://github.com/airbnb/enzyme

### CODE REVIEW

**Comment by joshnesbitt** [comment]
:shipit:

**Comment by romidane** [comment]
Can you update the package.json version too

**Comment by joshnesbitt** [comment]
Good shout @romidane

**Comment by smidhonza** [comment]
could we actually say that in CONTRIBUTING.md somewhere?

**Comment by thomaslloyd** [comment]
Updated :)

**Comment by joshnesbitt** [comment]
Done @smidhonza.

**Pull request merged**
