### PR TITLE
Use Karma + Mocha as the only testing framework

### PR DESCRIPTION
**Pull request by romidane**

### CODE REVIEW

**Comment by joshnesbitt** [comment]
@thomaslloyd do you mind testing this with the new specs you've been writing with mocha please?

**Comment by joshnesbitt** [comment]
@mackstar thoughts on using Karma to run Mocha? Maybe we should remove the option of multiple runners and pick one.

**Comment by thomaslloyd** [comment]
@joshnesbitt I haven't gotten around to converting our tests to Mocha yet! Plus I didn't think we needed karma to run mocha... is there an advantage to doing it this way?

 I also agree we should stick to one test runner. It will make working on multiple projects a lot easier.

**Comment by romidane** [comment]
The advantage is in the fact that all the configurations are in one place and it is easy to extend. Furthermore the is no more need to explicitly import you're assertions libraries to run your tests.

**Comment by joshnesbitt** [comment]
I'm in two minds about whether we just sack of Karma and just use Mocha on it's own...

**Comment by thomaslloyd** [comment]
@romidane I've never used Mocha properly so I may be wrong, but, I thought we could run Mocha directly and add config to the `environment.js` file, including the import of assertion libraries, without the need for Karma at all.

**Comment by romidane** [comment]
@thomaslloyd You can but that's more work in my opinion. The reason tools like karma exist is to ease the configuration of your test suites. It's much easier to maintain a Karma.conf file than having to create custom configuration through trial and error.

**Comment by thomaslloyd** [comment]
That's a very good point. :) I will see if your changes work in our component!

**Comment by romidane** [comment]
Yh please do ```blackjack test -r karma```

**Comment by joshnesbitt** [comment]
Sounds good. The agnostic side to karma is a nice potential win, but in practice changing test runners won't be as easy (as we'll use specific assertion libs etc). Happy to just move to Mocha if the general consensus is that though, we need to be defining a single clear path for tooling over giving options at this point.

**Comment by thomaslloyd** [comment]
@romidane @joshnesbitt The Karma conf here works for the tests in blackjack-forms now that I've converted them to Mocha.

**Comment by joshnesbitt** [comment]
Thanks for testing @thomaslloyd!

**Comment by thomaslloyd** [comment]
Could you add `'react/addons': true` to the `externals` section? The test command currently throws a bunch of errors (even though the tests all pass). There's an explanation for why it's needed [here][0].

[0]: https://github.com/airbnb/enzyme/blob/d31aeeb86ecb1503841c62c0669fbad899657763/docs/guides/webpack.md

**Comment by romidane** [comment]
Yeah sure thing 👍

**Comment by thomaslloyd** [comment]
@romidane  That's awesome, thanks!

I've also noticed that some of Chai's assertions are not playing well with the lint rules we have. Assertions such as `expect(val).to.be.ok;` throw the following error:

```
 error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

This is a [recognised issue][0] with es-lint. Do you think we could address this with the proposed solution of using [`dirty-chai`][1]?

[0]: https://github.com/eslint/eslint/issues/2102
[1]: https://github.com/prodatakey/dirty-chai

**Comment by mackstar** [comment]
The way that I see this is that where possible we will run mocha as default `stand-alone`. The only real reason I added Karma was to effectively run Jasmine tests. But I understand that if you actually want to run these tests through a specific browser then Karma does add benefit to Mocha.

So here is my suggestion:

1. Default testing `blackjack test` is Mocha directly
2. Testing `blackjack test --runner karma` is Jasmine run through Karma.
3. Testing `blackjack test --runner karma:mocha` is Mocha run through Karma.

We can then enlarge this to dynamically switch browsers eg.

4. Testing `blackjack test --runner karma:mocha --browser chrome`

What are your thoughts?

**Comment by romidane** [comment]
@thomaslloyd I've not used dirty-chai before but it feels kind like cheating to me if you have to use a non standard library just to pass the linting rules. Perhaps we can just add an exception to the linting rules?

@mackstar I though the idea is to standardize testing to use on test framework?

I like the idea being able to test the app of different browsers. But it would make it easy to just maintain one test framework don't you think?

So an easier to remember command to run tests in my opinion would be: 
```blackjack test ```
```blackjack test --browser chrome ```

And have all test run on Mocha?

**Comment by thomaslloyd** [comment]
@romidane Yeah that would be another option :)

**Comment by joshnesbitt** [comment]
@thomaslloyd after thinking about this I wonder whether we could add exceptions to the linter?

@mackstar I think we should force a single route for this, I think having mocha running via karma, and then standalone is confusing. If we go the karma route it allows for more flexibility in the future, and as you said we can then go down the multiple browser route for testing via an option.

If you're in agreement, I'll remove the `--runner` option, push everything through karma, and lay the groundwork for a few options such as the browser one you mentioned.

**Comment by joshnesbitt** [comment]
I've just pushed the discussed changes, which removes the runner option from the test command. As agreed, we're going with Karma + Mocha for our standard setup. I've omitted the `--browser` option for now as we don't have a use case for it. Happy to add it in another PR if we need.

@thomaslloyd & @romidane do you mind checking this works for you and you're happy with this?

**Comment by romidane** [comment]
Beautiful works like a charm 🎉 🎉

**Comment by joshnesbitt** [comment]
🎉  will wait on @thomaslloyd then merge if things are looking good.

**Comment by thomaslloyd** [comment]
@joshnesbitt They work for me! Seems all good. :)

**Comment by thomaslloyd** [comment]
:shipit:

**Pull request merged**
