### PR TITLE
Remove the need to include blackjack-toolbelt in components, add react dependencies

### PR DESCRIPTION
**Pull request by romidane**
* By adding 'resolveLoader' in to the config we tell blackjack to only use the node modules inside the blackjack tools to resolve mising dependencies
* This means that we no longer need to include blackjack-toolbelt in the components therefore speeding up build time tremendously

Install time with this new update:
```npm install  3.41s user 1.22s system 42% cpu 10.985 total```

Installation before this update
```npm install  105.88s user 20.03s system 53% cpu 3:54.64 total```

### CODE REVIEW

**Comment by thomaslloyd** [comment]
As an added bonus... that would fix this issue: https://github.com/sky-uk/blackjack-toolbelt/issues/34

**Comment by romidane** [comment]
* User don't even need to require react in their components. So I think it will be important to decided which dependencies come with the toolbelt and which one users will need to be explicit about. This is because if you just want the component to work on it's own then we probably want to have it in there

**Comment by romidane** [comment]
As a side note in order for this to work you have to run ```npm install to recompile the preview commands ``` in the blackjack-toolbelt repository.

The steps for a clean test for this feature is as follows
 * Remove node modules in both your component and blackjack tool belt
 ``` rm -rf node_modules```

* Remove blackjack-toolbelt from dependencies in the component
* Test it
``` blackjack test ```
``` blackjack preview```

Let me know how it goes  :)

**Comment by joshnesbitt** [comment]
This pull request is bang on 👍  

It addresses another conversation I've had with @mackstar about there being no dependency on the toolbelt for components. Agree React should be in the `package.json` for the component anyway, as it allows us to be explicit about what version the component was developed with. As @thomaslloyd said it also addresses a long standing issue of `npm run whatever` not working with the blackjack tools.

I'm really happy with this. Just need to check @mackstar is too and we'll get this merged. Thanks @romidane!

**Comment by joshnesbitt** [comment]
Bump @mackstar. @thomaslloyd does this work for you?

**Comment by mackstar** [comment]
@joshnesbitt Just been testing now, added a small tweak. Merging now..

**Comment by joshnesbitt** [comment]
Awesome thanks @mackstar. The reason React was left in there is that I think it's good to know what version the component was developed with. Happy to roll with this though.

**Comment by mackstar** [comment]
As discussed earlier with @joshnesbitt we may need to add back in the React hard dependency. Lets see how this goes?

**Comment by joshnesbitt** [comment]
Happy to see how this goes :)

**Comment by thomaslloyd** [comment]
@joshnesbitt We still need to get a bunch of these dependencies in the blackjack-forms project to run our webpack command.

**Comment by joshnesbitt** [comment]
@thomaslloyd anything I can do to help?

**Comment by romidane** [comment]
@thomaslloyd  have you ran ```npm run postinstall``` in your blacktool-belt repository?

**Comment by thomaslloyd** [comment]
@joshnesbitt Yeah, I think we need to have a think about how these components should be built for use in other projects. In `blackjack-forms`, we currently Webpack everything so that it's compiled down to ES5 andpoint it at an `index.js` that imports everything, meaning we can just do `import FormComponent from 'blackjack-forms'. Probably the best solution would be to create a `bj build` or `bj webpack` command.

@romidane Yeah I have and all the blackjack commands work fine with this PR pulled in. :)

**Comment by joshnesbitt** [comment]
@thomaslloyd yup @mackstar originally proposed a build command. I reckon we could add this pretty easily. Feel free to give it a go if you want!

**Comment by thomaslloyd** [comment]
@joshnesbitt Unfortunately I'm a bit stretched for time right now. Will drop you a message on slack.

**Comment by joshnesbitt** [comment]
Not a problem, was more if you wanted to have a crack and it was blocking you.

**Pull request merged**
