### PR TITLE
Remove polyfill from toolbelt, this should be managed by the target project

### PR DESCRIPTION
**Pull request by joshnesbitt**

### CODE REVIEW

**Comment by joshnesbitt** [comment]
@thomaslloyd I'd recommend giving this a go then try and resolve the polyfill issue in the target project. Maybe try a different polyfill for sanity.

**Comment by joshnesbitt** [comment]
@mackstar do you agree with this?

**Comment by mackstar** [comment]
I am happy with this yes!

**Comment by mackstar** [comment]
But... This will cause PhantomJS to fail, so we need to keep it I think.

**Comment by romidane** [comment]
I think the can be fixed by adding the necessary polyfills to the Karma config as follow.

``` npm instal phantomjs-polyfilll babel-es6 es6-promise object.assign ```

```
files: [
       './node_modules/phantomjs-polyfill/bind-polyfill.js',
       './node_modules/babel-es6/polyfill.js',
       './node_modules/es6-promise/dist/es6-promise.js',
       './node_modules/object.assign/dist/browser.js',
]
```
At least this way we know what is being polyfilled

**Comment by joshnesbitt** [comment]
Doh, you're right.

**Pull request closed without merging**
