### PR TITLE
Downgrading Enzyme version to fix bug

### PR DESCRIPTION
**Pull request by thomaslloyd**
I would like to temporarily downgrade the version of Enzyme due to [this issue][0] with SVGs. A bug was introduced in the most recent version causing a search for a classname to throw errors on any component that has an svg tag rendered in it:

```
mount(<svg />).find('.a');
```

throws

```
 undefined is not a constructor (evaluating 'classes.replace(/\s/g, ' ')')
```

My only concern with doing this is if people have started using the new features such as complex CSS selectors. 

[0]: https://github.com/airbnb/enzyme/issues/375

### CODE REVIEW

**Comment by joshnesbitt** [comment]
I think @romidane upgraded this, but wasn't sure if there was a reason? If not I'm happy to downgrade, we're not using any of those features.

**Comment by romidane** [comment]
@thomaslloyd and @joshnesbitt I don't mind downgrading it back down a version. I'm not currently using any of the new features. But It's worth while keeping an eye on a fix for this issue as it would be a shame to miss out on some of the improvements in the future 👍

**Comment by joshnesbitt** [comment]
Sounds good!

**Comment by thomaslloyd** [comment]
@romidane Yeah I was looking forward to simplifying some tests using the complex CSS selectors :( hopefully it will be fixed in the next release.

**Pull request merged**
